services:
  eureka:
    image: 'eureka-server:latest'
    build:
      dockerfile: Dockerfile
    container_name: eureka-server
    ports: 
      - "8761:8761"
    networks:
        - microservices-network
networks:
  microservices-network:
    external: true